/*
===============================================================================
Magnitude Analysis
===============================================================================
*/

-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM GOLD.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM GOLD.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM GOLD.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT 
category,
AVG(cost) AS average_cost
FROM GOLD.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
P.category,
SUM(F.sales_amount) AS total_revenue
FROM GOLD.fact_sales F
LEFT JOIN GOLD.dim_products P
ON P.product_key=F.product_key
GROUP BY category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM GOLD.fact_sales f
LEFT JOIN GOLD.dim_customers c
ON c.customer_key=F.customer_key
GROUP BY c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT 
country,
SUM(quantity) AS total_sold_items
FROM GOLD.fact_sales f
LEFT JOIN GOLD.dim_customers c
ON c.customer_key=f.customer_key
GROUP BY country 
ORDER BY total_sold_items DESC;

